### ISSUE TITLE
Práctica de Planificación de recursos

### ISSUE THREAD

**Issue by Edwin-1012** [SistemasTecTlaxiaco/practica-planificacion-de-recursos-entrevista-gp#1]
[Planificación de recursos.pdf](https://github.com/SistemasTecTlaxiaco/practica-planificacion-de-recursos-entrevista-gp/files/7557048/Planificacion.de.recursos.pdf)

**Comment by Jaci14** [comment]
Cumple con el objetivo de la practica, el EDT es entendible y realiza un buen cronograma de actividades para maximizar la eficiencia de las actividades.

Calificación: 20%

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
