### ISSUE TITLE
Práctica de Gestión de Riesgos

### ISSUE THREAD

**Issue by Edwin-1012** [SistemasTecTlaxiaco/practica-planificacion-de-recursos-entrevista-gp#2]
[Práctica Gestión de Riesgos_Edwin, Alexis, Iván, Taoli.pdf](https://github.com/SistemasTecTlaxiaco/practica-planificacion-de-recursos-entrevista-gp/files/7557066/Practica.Gestion.de.Riesgos_Edwin.Alexis.Ivan.Taoli.pdf)

**Comment by Jaci14** [comment]
Cuenta con todos los puntos requeridos en la practica, el reporte cuenta con una buena estructura y la matriz de analisis de riesgos es legible. 
Calificacion: 20%.

**Comment by Jaci14** [comment]
Cuenta con todos los puntos requeridos en la practica, el reporte cuenta con una buena estructura y la matriz de analisis de riesgos es legible. 
Calificacion: 20%.

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
